### ISSUE TITLE
document magic numbers

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#110]
There are a few magic numbers in `GasPropertiesConstants` that are related to the non-standard units that we used in the model.  See below.  I think it would be good to provide the calculations somewhere - perhaps in model.md, or even just a scan of a piece of paper.  @arouinfar do you still have your notes for these computations? 

```js
    // physical constants
    BOLTZMANN: 8.316E3, // Boltzmann constant k, converted to (pm^2 * AMU)/(ps^2 * K) by @arouinfar

    // conversion factors, provided by @arouinfar
    KG_PER_AMU: 1.66E-27, // mass conversion: kg per 1 AMU (atomic mass unit)
    ATM_PER_KPA: 0.00986923, // pressure conversion: atm (atmospheres) per 1 kPa (kilopascal)
    PRESSURE_CONVERSION_SCALE: 1.66E6 // multiplier for converting pressure from AMU/(pm * ps^2) to kPa
```

**Comment by arouinfar** [comment]
@pixelzoom kg to AMU and atm to kPa are pretty standard unit conversions, so I don't think we need to include them in model.md. I do, however, think we should show the calculations for the Boltzmann constant and pressure conversions (since these are non-standard units, requiring multi-step conversion). I'm not sure that I can make a decent looking equation in a markdown file, so here are some screenshots, instead.

<img width="1091" alt="Screen Shot 2019-06-06 at 4 51 11 PM" src="https://user-images.githubusercontent.com/8419308/59071382-998cb080-887b-11e9-8b16-2fc8936ee7aa.png">

![image](https://user-images.githubusercontent.com/8419308/59071383-9a254700-887b-11e9-9553-c25b26073317.png)

**Comment by pixelzoom** [comment]
> kg to AMU and atm to kPa are pretty standard unit conversions, so I don't think we need to include them

Right, sorry they got lumped in there.  And I should change the doc, I believe that Google provided them :)

> ...  so here are some screenshots

Perfect, thanks!  I'll check this screenshot into GitHub, then reference it from model.md.

**Comment by pixelzoom** [comment]
Done, closing.
