### ISSUE TITLE
Should erase button be color other than grey?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gas-properties#120]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/342
I had two problems with the current eraser button.  First, the difference between it being clickable and not is rather hard to see.  Second, the grey image on a grey background can make it a bit hard to see what the button is.

**Screenshots:**
![notdifferentenough](https://user-images.githubusercontent.com/41024075/59312195-755d1500-8c69-11e9-92ea-24754ee2bfa7.gif)

Troubleshooting information (do not edit):

<details>

Name: ‪Gas Properties‬
URL: https://bayes.colorado.edu/dev/html/gas-properties/1.0.0-dev.38/phet/gas-properties_all_phet.html
Version: 1.0.0-dev.38 2019-06-11 17:16:28 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment]
@KatieWoe thanks for reporting. The design issue for the erase button is https://github.com/phetsims/gas-properties/issues/91, and it was added fairly recently.  I believe that it started life as the standard "PhET yellow" button, which certainly stood out.  But then the goal became to make it purposefully not stand out. As you can see, we went through a number of colors before deciding on the current `rgb( 220, 220, 220 )`.   @arouinfar let me know if you'd like to revisit.

**Comment by pixelzoom** [comment]
I'm also going to change the label on this from "bug" to "design:general", since it was a conscious design decision and the implementation matches the specification.

**Comment by arouinfar** [comment]
Thanks @KatieWoe, and thanks for the explanation @pixelzoom.

The button is gray so that it doesn't draw too much attention to itself. We have previously used an even lighter gray erase button for a similar purpose in Unit Rates, which had no flow issues in interviews.
![image](https://user-images.githubusercontent.com/8419308/59365746-4e98f000-8cf6-11e9-9a2f-b0d366ff43ac.png)

@KatieWoe as a part of the regular interview process, I will be looking out for UI components that students overlook. If I observe any issues with the erase button, we will revisit its color.

However, since the current design was intentional, I'm going to close.
