### ISSUE TITLE
consider adding FixedWidthNode to common code

### ISSUE THREAD

**Issue by veillette** [phetsims/gas-properties#137]
FixedWidthNode is used more than 10 times in the simulations.  Many simulations have It is a very useful idea for Panel, AccordionBox , etc, that need to be of the same width. This is a design requirement that is rather widespread and found in multiple simulations. 

It is also useful for panels /accordion box that need to have the same width from one screen to the other but may have slightly different content.  

@brandonLi8 did a deep copy of it in vector-addition.  Before this practice spreads too far, perhaps we should consider moving this module in common code. I don't know how much work it would entail, but the module is already written in a very generic way with type validation. 

Any thoughts @pixelzoom ?

**Comment by pixelzoom** [comment]
I'm fine with moving `FixedWidthNode` to a common repo (scenery-phet?)  

But as noted in the doc for `FixedWidthNode`:

> * A solution using AlignGroup and AlignBox was investigated, but they do not address horizontal separators
 * they do not handle container margins, and their width is dictated by the largest component vs a specified width.

So we might need to have a dev discussion about the types of problems that AlignBox/AlignGroup solves, and why it's not working out for other types of problems.  In general, I feel like PhET common code is a bit lacking/awkward in the area of layout managers.  

@veillette thoughts?

**Comment by veillette** [comment]
I'm not wedded to FixedWidthNode but the functionality of having a nodes with fixed width is very convenient and is often a requirement of the design team.

I agree that we should get this issue on the developer meeting agenda.

**Comment by brandonLi8** [comment]
Update @veillette, Vector Addition no longer uses `fixedWidthNode`. Panels support a minWidth/ maxWidth and I used alignBox on the `vectorCreatorPanel` to set both a fixed width and a fixed height.

**Comment by pixelzoom** [comment]
Thanks for the update @brandonLi8.

Since gas-properties is still the only sim to be using this, I don't think there's any urgency to moving this to common code.  PhET typically moves things to common code when a second sim needs something.  And this is certainly not a prerequisite to publishing 1.0.0.

Still happy to have a dev meeting discussion about the general feature.

**Comment by pixelzoom** [comment]
@brandonLi8 said:
> ... Panels support a minWidth/ maxWidth ...

I guess I could also investigate using `Panel` in place of `FixedWidthNode`, although putting a `Panel` inside of an `AccordionBox` seems odd.

**Comment by pixelzoom** [comment]
I made an attempt at replacing FixedWidthNode with AlignGroup and AlignBox.  It seemed like it would be doable, but it was much more complicated and less obvious about what was going on.  And I had to start doing "clever" things to get horizontal separator to fill the full width.  I think it's much clearer to be able to say "I want my content to always be this wide".   So I reverted.

**Comment by pixelzoom** [comment]
@veillette said:
>  ...  I don't know how much work it would entail, but the module is already written in a very generic way with type validation.

There are a couple of things that `FixedWidthNode` currently does not support:
* dynamic `content` bounds (would require updating alignment on bounds change)
* additional children other than `content` (it assumes that `content` is its only child)

**Comment by pixelzoom** [comment]
I've moved the general issue (how to create fixed-width panels) to https://github.com/phetsims/scenery/issues/985, and labeled it for discussion at developer meeting. If that issue gets addressed before Gas Properties 1.0.0 enters RC testing, then I'll replace `FixedWidthNode`.  If not, then I'll publish with `FixedWidthNode`.

**Comment by pixelzoom** [comment]
Discussed with @jonathanolson on Zoom.  

We agree that this functionality does not belong in AlignBox or AlignGroup -- they deal with alignment.  And AlignGroup does not address this problem.  You could effectively get the same behavior by adding an `HStrut` (to set min width) and setting AlignBox's `maxWidth`, but it's a little less obvious, and (in the case of Gas Properties) involves sharing an AlignGroup across screens.

`FixedWidthNode` seems like a reasonable way to do this, but lacks a couple of general features as noted in https://github.com/phetsims/gas-properties/issues/137#issuecomment-506755851.   Since no other sims currently use this, I'm not going to spend the time to generalize now, and will address if/when needed by another sim. 

Closing.
