### ISSUE TITLE
Pressure changes when sim paused

### ISSUE THREAD

**Issue by jbphet** [phetsims/gas-properties#142]
I noticed this while working on the code review in #111, and it is related to #11.  If the pressure is at zero and the sim is paused, adding particles in any of the first three screens does not cause the pressure to increase.  However, if the pressure is non-zero and the sim is paused, adding particles *does* cause the pressure to go up.  This is inconsistent at the least, but also seems physically incorrect to me - pressure should not be allowed to change if no time is passing.

**Comment by jbphet** [comment]
Assigning to @arouinfar first to make sure that the behavior is not intentional for some reason.

**Comment by arouinfar** [comment]
There are a few things at play here @jbphet. First, the pressure in the view is zero until the first particle-wall collision. Second, for a variety of reasons best described in #60 (particularly https://github.com/phetsims/gas-properties/issues/60#issuecomment-498858782 onwards), the model immediately updates when the sim is paused. 

One of the learning goals for the sim is that pressure arises from particle-wall collisions, which is why we added the Collision Counter tool. It looks very strange for the pressure gauge to immediately jump from zero to the pressure calculated in the model `P = NkT/V`, even though no particles have collided with the container walls. As a compromise, we decided to keep the update the pressure in the view to the model value only after the first particle-wall collision. While this isn't perfectly accurate, the design team felt that it was a reasonable compromise.

The behavior is Java is somewhat similar -- when adding particles to the container, it takes a little while for the pressure to build up. That said, the Java implementation of the pressure gauge is actually quite convoluted and has nothing to do with the ideal gas law, but the effect in the view is similar.

> However, if the pressure is non-zero and the sim is paused, adding particles does cause the pressure to go up. This is inconsistent at the least, but also seems physically incorrect to me - pressure should not be allowed to change if no time is passing.

What's happening here is that changing N has an immediate effect on P, even when paused, due to the changes made in #60. While I agree that it's somewhat inconsistent, I think there are stronger pedagogical reasons for leaving the behavior the way it is.

Adding particles while the sim is paused immediately adds the particles to the container, and they can be seen at the end of the `BicyclePumpNode` hose. The model has no choice but to include these particles in the pressure calculation.
![image](https://user-images.githubusercontent.com/8419308/60848811-5e94da00-a1a5-11e9-9536-26d962e51b68.png)

If the container pressure is already non-zero in the view, these newly added particles will result in an increased pressure reading. The same is true if particles are removed from the container while paused. N has changed, and therefore P must be recalculated.



Happy to discuss this more @jbphet, please let me know if you have any further questions/concerns.

**Comment by jbphet** [comment]
Sounds reasonable.  Closing.
