### ISSUE TITLE
Units of pressure

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/gas-properties#169]
> In the simulation Gas Properties HTML5 we can use for units of pressure kPa and atm.
> In Europe we use mbar = hPa.
> Atm is replaced by bar because atm is no SI unit.
> 
> Can you add mbar/hPa as  unit for pressure?

**Comment by pixelzoom** [comment]
bar is also not an approved SI unit, see https://en.wikipedia.org/wiki/Bar_(unit).

1 mbar = 0.1 kPa, so I'm not convinced that adding mbar units would be a valuable addition.

**Comment by arouinfar** [comment]
The Pa is the SI unit for pressure, although 1 Pa is pretty small. Generally, atmospheric pressures are expressed in mbar, but since that's so close to kPa (and would add extra digits to the pressure reading) I'm also inclined to pass for now. However, if this ends up being a common request, we may want to add mbar as an option.

I'll close this for now, but @oliver-phet if you end up getting more requests for mbar, please reopen this issue.

**Comment by pixelzoom** [comment]
Notes for the future on how to add mbar, which is relatively straightforward:

* Add `@public {DerivedProperty} presureMbarProperty` to `PressureGauge` constructor
* Add `MBAR` to `PressureGauge.Units`
* Add `MBAR` related "choice" to `items` in `PressureDisplay` constructor
* Add "mbar" string to gas-properties-strings_en.json

**Comment by pixelzoom** [comment]
Reopening to make sure that @oliver-phet has followed up with the user who requested this feature. @oliver-phet please close when that's been done.

**Comment by oliver-phet** [comment]
Replied to user.
