### ISSUE TITLE
Generalize Stopwatch and StopwatchNode

### ISSUE THREAD

**Issue by samreid** [phetsims/gas-properties#170]
The design for Circuit Construction Kit: AC calls for a stopwatch.  I noticed that gas-properties/js/common/model/Stopwatch.js and gas-properties/js/common/view/StopwatchNode.js look like good candidates for generalization.  They have features that most other sims will need to leverage as well, including moveToFront, interrupting user interactions, dragging, drag bounds, etc.  I would be duplicating most of this for the development for CCK, and some of this may already be duplicated in other sims with draggable stopwatches.  The main sim-specific parts (units and color) could be moved to options.

Discovered in conjunction with https://github.com/phetsims/scenery-phet/issues/530

@pixelzoom what do you think?

UPDATE: Tagging for https://github.com/phetsims/circuit-construction-kit-common/issues/449

**Comment by pixelzoom** [comment]
This seems reasonable. But I won't have time to evaluate for about a week.  In the meantime, gas-properties is in the middle of RC testing for a maintenance release. I'd appreciate it if we didn't make changes to gas-properties master until that maintenance release is published, because it may complicate cherry picking.

**Comment by pixelzoom** [comment]
By the way... There are a couple of things that I really don't like about `StopwatchNode`, issues that are rooted in `TimerNode` and `TimerReadoutNode`:

* The timer stops when it reaches a max. It would be OK as an option (not sure when I'd want to use it) but it's unacceptable as the only behavior.  Imo, a design flaw.
* The value display is not general.  It can only show "HH:MM:SS" or a value to 2 decimal places.  For example, if I wanted to show only "5 ps" or "5.3 ps" (which would have been nice) in Gas Properties, then I'm out of luck.   This smells like something that was sim specific and not properly generalized.

**Comment by pixelzoom** [comment]
I said:
> ...  I'd appreciate it if we didn't make changes to gas-properties master until that maintenance release is published, because it may complicate cherry picking.

When I wrote that, Gas Properties 1.0.1 RC testing was close to completion.  But it has now been downgraded to "medium" priority (see https://github.com/phetsims/QA/issues/415#issuecomment-528464479) and the QA queue looks pretty full.  https://github.com/phetsims/circuit-construction-kit-common/issues/449 is "Publish CCK AC 1.0 by January 31, 2020" so maybe that's OK.   Mentioning @samreid and @ariel-phet, in case there needs to be any priority adjustment.

**Comment by pixelzoom** [comment]
`Stopwatch` looks like it's already generalized. It has no dependencies on `GAS_PROPERTIES` other than namespace.  

`StopwatchNode` does have dependencies on  `GAS_PROPERTIES` 
* `GasPropertiesQueryParameters.origin` can just be deleted, or replaced with `?dev`.   
* `GasPropertiesColorProfile.stopwatchBackgroundColorProperty` can be replaced (and deleted) with `'rgb(  80, 130, 230  )'`, unless there's a general need to dynamically change background color.
* `DragBoundsProperty` could be moved into StopwatchNode.js as an inner class, but it's also used by `CollisionCounterNode`,

Assigning back to @samreid.  Feel free to proceed when Gas Properties 1.0.1 has been published, addressing (or not) concerns that I noted in https://github.com/phetsims/gas-properties/issues/170#issuecomment-528394405 as the design team sees fit.

**Comment by pixelzoom** [comment]
One thing that I just noticed...  All `Stopwatch` Properties are instrumented for PhET-iO.  One of those Properties is `this.visiblePropery`, which may be irrelevant (or undesirable for instrumentation) if you are dragging the Stopwatch out of a toolbox.  In Gas Properties, visibility was controlled via a checkbox, and `StopwatchNode` observes this Property.  Not sure what you'll want to do here design-wise.

**Comment by samreid** [comment]
Tagging as potential work for https://github.com/phetsims/circuit-construction-kit-common/issues/528

**Comment by samreid** [comment]
> Assigning back to @samreid. Feel free to proceed when Gas Properties 1.0.1 has been published

Gas Properties 1.0.3 has been published.  I'll take a look around.

**Comment by samreid** [comment]
Note that the proposed renamings in https://github.com/phetsims/scenery-phet/issues/530 will affect how this work can be done, since there could be naming collisions.

**Comment by pixelzoom** [comment]
I understand that work has resumed on this.  Are you addressing any of the problems identified in https://github.com/phetsims/gas-properties/issues/170#issuecomment-528394405?

**Comment by samreid** [comment]
I reviewed both of those requests but have not begun investigating them.  My initial commits will focus on:

* moving Stopwatch to scenery-phet
* renaming SCENERY_PHET/TimerNode to SCENERY_PHET/StopwatchNode
* Adding features from GAS_PROPERTIES/StopwatchNode to SCENERY_PHET/StopwatchNode and adapting the API accordingly
* Updating all simulation to use the new API

**Comment by samreid** [comment]
I've completed an initial pass of this work, I'll begin commits and pushes.  I've marked several TODOs referring to this issue which should be done after initial pushes, or, in many cases, converted to new issues.

**Comment by samreid** [comment]
I opened issues for other repos where review will be required.  I'll now push changes for Gas Properties and common code changes linked to this issue.  Note there are still 9 TODOs marked referencing this issue.  As noted above, these should addressed after initial pushes, or converted to issues.  I'm still working on this and will reassign to @pixelzoom once it's ready for review.  I'll hold off on requesting reviews in the other repos (linked above) until this issue is complete, so we can make sure the API is finalized.

**Comment by pixelzoom** [comment]
I know this is not "review ready", but a couple of quick notes above the above commits...

(1) In https://github.com/phetsims/gas-properties/commit/f19e5619e1e21fad251700c3ed87d763c1945f13, GAS_PROPERTIES/BaseModel is using a hardcoded string literal: `units: 'ps'`.   Please require 'AXON/units' and use `units.ps`.

(2) I see that `visibleProperty` has been changed to `isVisibleProperty`.  I get it that the "is" prefix is a reasonable convention for boolean Properties.  But scenery uses `visibleProperty`, and it's used everywhere, so I'm very much in the habit of reaching for `visibleProperty`.  Another example is `enabledProperty`, also used everywhere.  So there's a trade-off here, and I don't think that changing to `isVisibleProperty` comes down on the "net gain" side of that trade-off.  Unless you're going to change `visibleProperty` _everywhere_, I think it's better to stick to what is used (almost?) everywhere.

**Comment by samreid** [comment]
> (1) In https://github.com/phetsims/gas-properties/commit/f19e5619e1e21fad251700c3ed87d763c1945f13, GAS_PROPERTIES/BaseModel is using a hardcoded string literal: `units: 'ps'`.   Please require 'AXON/units' and use `units.ps`.

I addressed that in the preceding commit.

> (2) I see that `visibleProperty` has been changed to `isVisibleProperty`.  I get it that the "is" prefix is a reasonable convention for boolean Properties.  But scenery uses `visibleProperty`, and it's used everywhere, so I'm very much in the habit of reaching for `visibleProperty`.  Another example is `enabledProperty`, also used everywhere.  So there's a trade-off here, and I don't think that changing to `isVisibleProperty` comes down on the "net gain" side of that trade-off.  Unless you're going to change `visibleProperty` _everywhere_, I think it's better to stick to what is used (almost?) everywhere. 

It seemed odd to have `visibleProperty` adjacent to `isRunningProperty` in Stopwatch.js.  I also recalled a more recent consensus that boolean attributes and properties should typically begin with `is`, but I do not know where to find a paper trail on this, or whether we have cited an exception for `visibleProperty`.  Let's discuss further.

I'm now wondering if we should change NodeIO.js `visibleProperty` to `isVisibleProperty`.  Should I open a new issue to deliberate on that?

**Comment by samreid** [comment]
> GasPropertiesQueryParameters.origin can just be deleted, or replaced with ?dev.

I set this to run with `?dev`.

> GasPropertiesColorProfile.stopwatchBackgroundColorProperty can be replaced (and deleted) with 'rgb( 80, 130, 230 )', unless there's a general need to dynamically change background color.

I set that as the default, and gas properties supplies:

```js
backgroundBaseColor: GasPropertiesColorProfile.stopwatchBackgroundColorProperty,
```

> DragBoundsProperty could be moved into StopwatchNode.js as an inner class, but it's also used by CollisionCounterNode,

I moved this to scenery-phet as a top-level class.

> One thing that I just noticed... All Stopwatch Properties are instrumented for PhET-iO. One of those Properties is this.visiblePropery, which may be irrelevant (or undesirable for instrumentation) if you are dragging the Stopwatch out of a toolbox. In Gas Properties, visibility was controlled via a checkbox, and StopwatchNode observes this Property.

It seems appropriate to instrument these properties, even when using a toolbox pattern.

What's been committed so far is ready for review.  @pixelzoom are you available to review this work?  Please note there are 4 TODOs marked with `https://github.com/phetsims/gas-properties/issues/170` that I'd like feedback on (one in DragBoundsProperty and 3 in StopwatchNode).

**Comment by samreid** [comment]
I saw some issues on CT I'd like to address before review.  Reassigned to me.

**Comment by samreid** [comment]
I updated phet-io concerns in the above commits.  Back to @pixelzoom for review.

**Comment by pixelzoom** [comment]
There are a lot of commits here.  As far as I can tell, I’m reviewing `Stopwatch`, `StopwatchNode`, `StopwatchReadoutNode`, `DragBoundsProperty`, and `ComponentsScreenView` (all in scenery-phet).  If I missed any, please point them out.    

Due to lack of time, I am not going to review the changes that were made to sims other than Gas Properties. If that's necessary, please assign to responsible developers. All changes to Gas Properties look good.

Review comments...   

- [ ] `Stopwatch` has option `location` and Property `positionProperty`. I would have stuck with `locationProperty` (in the original implementation) until https://github.com/phetsims/phet-info/issues/126 was discussed/addressed. 

```js
this.positionProperty = new Vector2Property( options.location, {
```

- [ ] `Stopwatch` now has `isVisibleProperty` instead of `visibleProperty`.  I prefer the latter, as noted in https://github.com/phetsims/gas-properties/issues/170#issuecomment-566717417.

- [ ] This `merge` call in `Stopwatch` allows the caller to override `tandem`.  Do we really want to allow that?  It will be awkward to make timeProperty’s `tandem` appear like its a sub-element of `options.tandem`.  And is there really a need, or is standardization better here?  Recommended to add `assert( !options.timePropertyOptions.tandem, ... )` before this `merge` call.

```js
      // @public (read-only) time displayed on the stopwatch
      this.timeProperty = new NumberProperty( 0, merge( {
        units: 's',
        isValidValue: value => ( value >= 0 ),
        tandem: options.tandem.createTandem( 'timeProperty' ),
        phetioReadOnly: true,
        phetioHighFrequency: true
      }, options.timePropertyOptions ) );
```

- [ ] `Stopwatch` has a hardcoded string for units.  I can’t imagine any scenario where untranslated ’s’ is an acceptable default.  If having a default is necessary/appropriate, it should be factored out into scenery-phet-strings_en.json.

```js
this.timeProperty = new NumberProperty( 0, merge( {
  units: 's',
```

- [ ] Documentation for `Stopwatch.step` is incorrect, vestigial from Gas Properties.  The units for dt are up to the client, not “in ps”.

```js
 * @param {number} dt - time delta, in ps

```

- [ ] Doesn’t `Stopwatch` need a `dispose` method? It registerers tandems for many Properties, all of which need to be disposed in order to deregister. 

- [ ] StopwatchNode has multiple memory leaks:
* `stopwatch.isVisibleProperty.link` and `stopwatch.positionProperty.link` both need a corresponding `unlink`
*  `this.dragListener` registers a tandem and needs to be disposed
* anonymous `new DragListener` registers a tandem and needs to be disposed
* `this.disposeStopwatchNode` definition should be moved towards the end of the constructor, after all of the things that it needs to clean up.

- [ ] In `ComponentsScreenView`, the `mutableUnitsStopwatchNode` does not run. It would be nice if it did, feels buggy.

TODOs...

- [ ] Re this TODO in StopwatchNode... Sorry, I don't know why either. I've never had a problem using `interruptSubtreeInput` to interrupt interactions.

```js
        // TODO: https://github.com/phetsims/gas-properties/issues/170 interrupting input was incompatible with dragging out of a toolbox
        // in wave interference, but not in Energy Skate Park: Basics, but I can't figure out why.
```

- [ ] Re these TODOs in StopwatchNode...

```js
      // TODO: This is from masses and springs, is it necessary in common code, or should it be specified via an option?
      // TODO: If so, how should the option be named or structured? See https://github.com/phetsims/gas-properties/issues/170
      this.touchArea = this.localBounds.dilated( 10 );
```

Definitely not cool to dilate the entire stopwatch because of Masses and Springs, and I don't see any need for an option since it's the touchArea for the entire `StopwatchNode `.  The stopwatch is huge in Masses and Spring, and I don't know why it would need a dilated touchArea. But it should be set `MASSES_AND_SPRINGS/SpringScreenView`, not in `StopwatchNode`:

```js
175 this.stopwatchNode = new StopwatchNode( model.stopwatch, {
...
this.stopwatchNode.touchArea = this.stopwatchNode.localBounds.dilated( 10 );
```

- [ ] Re this TODO in `DragBoundsProperty`…. Yes.

```js
// TODO: https://github.com/phetsims/gas-properties/issues/170 Should we also detect changes in the size of the
// target node itself?
```

**Comment by samreid** [comment]
> Stopwatch has a hardcoded string for units. I can’t imagine any scenario where untranslated 's' is an acceptable default. If having a default is necessary/appropriate, it should be factored out into scenery-phet-strings_en.json.

The units specified to a model property are not internationalized.  In the preceding commit, I corrected a problem in Gas Properties where it was treating units as an `Enumeration`.  But I'm wondering if AXON/units should be converted to an enumeration.  What do you think?

**Comment by pixelzoom** [comment]
Thanks for catching the Gas Properties problem.

I don't think `units` should be changed to an Enumeration, because I think we'd prefer to see 'm/s^2' rather than 'METERS_PER_SECOND_SQUARED' in the Studio and the PhET-iO data stream.

**Comment by samreid** [comment]
> Re this TODO in StopwatchNode... I've never had a problem using interruptSubtreeInput to interrupt interactions. 

In wave interference, if `interruptSubtreeInput` was called when the node is made visible, it triggered a re-entrant property.  So for the common code, `interruptSubtreeInput` is only called when the node is hidden (this is different than how it was for gas properties alone).

**Comment by pixelzoom** [comment]
That seems fine.  `interruptSubtreeInput` only really needs to be called when something becomes invisible.   In Gas Properties, there was no harm in calling it whenever visibility changed, and it simplified the logic.

**Comment by samreid** [comment]
Thanks for the review, I think I addressed each of the recommendations, some here and others in related issues referenced above.  Back to @pixelzoom for feedback.

**Comment by pixelzoom** [comment]
There are still problems in both Stopwatch and StopwatchNode.  

In Stopwatch, you didn't follow the pattern of putting disposal in `this.disposeStopwatch`, and `dispose` was missing override annotation.  Since those fixes were straightforward, I handled them in the 2 commits above.

In StopwatchNode:

- [ ] There's no need for `this.dragListener`, it can be `let dragListener`.  

- [ ] Comment "may be reassigned below, if draggable" is incorrect.  "May be assigned below if dragging is constrained to bounds".   

- [ ] Anonyomous `new DragListener` is still not cleaned up, and is leaking because it registers a tandem.  You need to keep a reference to it and dispose of it.

**Comment by samreid** [comment]
> Comment "may be reassigned below, if draggable" is incorrect. "May be assigned below if dragging is constrained to bounds".

Those are conflated at the moment, the docs for that option are:

```js
visibleBoundsProperty: null, // {Property.<Bounds2>|null} if provided, the node is draggable within the bounds
```

That is to say, if visibleBoundsProperty is not provided, the node is not draggable at all.  How do you recommend to proceed?

**Comment by samreid** [comment]
> There's no need for this.dragListener, it can be let dragListener.

I made that change in https://github.com/phetsims/scenery-phet/commit/e3f49a717163355dc1ee3fdcca4302644d266cf5 then CT pointed out that it is used for drag forwarding.  So restored it in https://github.com/phetsims/scenery-phet/commit/49c38f2a25b691e3f08086ea809c0333504ac3ed and annotated it as `@public`.

**Comment by pixelzoom** [comment]
> CT pointed out that it is used for drag forwarding

Where is `this.dragListener` used for drag forwarding?  And is it wise to make something that part of the public API when it may be `null`? 

> if visibleBoundsProperty is not provided, the node is not draggable at all. How do you recommend to proceed?

Sounds like a bug.  If there are no drag bounds, then StopwatchNode should still be draggable, with no constraints on the drag bounds.

**Comment by samreid** [comment]
Would you recommend a boolean `isDraggable` option?  Would you mind a check that if `isDraggable` is true, that the `visibleBoundsProperty` is required, at least until we have our first sim design where the timer should be draggable out of bounds?

**Comment by pixelzoom** [comment]
I guess we can still with `visibleBoundsProperty`, since I don't see a need to drag outside the visible bounds.  Just bringing it up because that wasn't my original intention when I added this feature for Gas Properties.

Thanks for clarifying about `this.dragListener`, current API seems reasonable.  Might be nice to add a comment about why it's `@public`.

**Comment by samreid** [comment]
Good idea, I added a note.  Anything else to do for this issue?

**Comment by pixelzoom** [comment]
Looks good.  Thanks for tackling this issue.  Closing.
