### ISSUE TITLE
PhetioID alredy registered

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gas-properties#179]
For ES6 Testing. Found in Gas Properties, Gases Intro, States of Matter, and States of Matter Basics. If you try to load the sim in studio or most other wrappers it freezes during loading and shows this error:
![gaspropbug](https://user-images.githubusercontent.com/41024075/75820726-1a6cd000-5d5a-11ea-931b-6062ff3e4ddb.png)

**Comment by pixelzoom** [comment]
@KatieWoe I believed this has been fixed in https://github.com/phetsims/scenery-phet/issues/579. See also https://github.com/phetsims/gas-properties/issues/147#issuecomment-590598415 and https://github.com/phetsims/gas-properties/issues/147#issuecomment-594138626.   If it's still a problem, assign back to me.  Otherwise please close.

**Comment by KatieWoe** [comment]
States of Matter is still running into a problem:
![statesproblem](https://user-images.githubusercontent.com/41024075/75897440-c9aab500-5df5-11ea-8c74-9b2ccbf085d9.png)

**Comment by pixelzoom** [comment]
@KatieWoe  This is unrelated to the HeaterCoolerNode problem that was originally reported.  Please create a new issue for SOM.
