### ISSUE TITLE
Escaping particles can teleport back into the container despite clear path out

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gas-properties#20]
For #8. A user reported in [Unfuddle Ticket #3493](https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3493):
> My students were playing with the gas properties simulation and noticed what may be a bug or may be a feature, we're not sure. I... did notice that for small numbers of particles the gas particles would spontaneously bounce back in.

@emily-phet replied (pre-SOM port):
> It is true that particles can bounce back in when it looks like they have a clear trajectory out of the box. I don't think this is worth fixing, States of Matter has the same issue.  I don't recall the exact reasons, but we did discuss them for States of Matter and decided it was ok to have it this way.

Here's a screen capture showing an escaping particle that teleports back into the container.
![unfuddle3493](https://user-images.githubusercontent.com/8419308/36756890-8647849e-1bcd-11e8-9b91-49b1b5a3b00b.gif)

This behavior looks pretty buggy to me, so I think it's worth investigating @pixelzoom. Perhaps @jbphet encountered something similar when porting States of Matter?

**Comment by pixelzoom** [comment]
Cool. @jbphet did you see anything like this when porting States of Matter?

**Comment by jbphet** [comment]
SOM didn't have exactly this problem, but something similar.  In general in particle simulations it's often a problem that a large time step and high velocity can cause a particle to end up outside of a container, since it can go from being so far from the container wall that no interaction occurs to the other side of the wall in a single step.  There was probably something built into the Gas Properties (GP) model code to detect this situation and "teleport" the particle back inside.  In this particular case, the particle is moving through an opening in the container, but ending up on the outside of the wall at the container's edge, and I'm surmising that this is causing the teleportation code to kick in.

**Comment by pixelzoom** [comment]
After implementing the collision detection in 1.0.0-dev.4, I'm confident that this bug has not been ported from Java to HTML5, and will not occur in HTML5.  Closing.
