### ISSUE TITLE
Alt Input support

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#213]
@kathy-phet asked to evalute alt input for https://github.com/phetsims/gas-properties/issues/191.

From a Slack conversation with @kathy-phet @arouinfar @pixelzoom:

@kathy-phet 
Let's evaluate alt input and UI sound, and see if there are any challenges there.

@arouinfar 
Alt Input might be tricky. The BicyclePumpNode will need common code work and the movable container wall would benefit from multiple speeds, which KeyboardDragListener doesn’t support. It was proposed in https://github.com/phetsims/scenery/issues/1601 and was deferred/closed.

@pixelzoom:
For alt input, the following interactions would be sim-specific, not provided by common code:
* resizing the box (multiple speeds?)
* opening the lid on the box
* operating the bicycle pump
* moving the collision detector
* moving the stopwatch

@kathy-phet 
OK. I think we should plan on alt-input work, and as we do that alt-input prioritization board in Monday, we can prioritize these for work in time for the sim schedule?

**Comment by pixelzoom** [comment]
Alt Input is now "on" for all sims in this suite.  pdomOrder is not being set, so focus order defaults to the order that Nodes are added to the scene graph.

**Comment by pixelzoom** [comment]
In the above commits, I set an initial pdomOrder by adding everything to the Control Area, as elements appear from left-to-right, top-to-bottom on the screens.   @arouinfar please let me know how you'd like things divided between Play Area and Control Area, and what the order should be.

Sim-specific things that are missing alt input:
- [ ] Lid handle on the container
- [ ] Resize handle on th container

Common-code things that are missing alt input, this work needs to be scheduled:
- [ ] BicyclePumpNode
- [ ] FineCoarseSpinner - in Particles accordion boxes. Is this how we want alt input to work forr this UI component?

**Comment by terracoda** [comment]
@pixelzoom, I agree, I think the FineCoarseSpinner is a number spinner type interaction. I think the number spinners In GFLB and RaP are implemented like discrete sliders.

**The FineCoarseSpinner** adds a second mode to the number spinner - a single-release and bunch-release. This could be handled in different ways, so it would be good to discuss options. 

One option is to make 2 tab stops (like two separate number spinners on top of each other) and have one release singles and the other release bursts, but both share the same model value total. The first Tab Stop encases the single buttons, the second Tab Stop encases the burst buttons.

Option two could use custom modifier keys on a single number spinner to release singles or bursts. E.g. arrow keys -> singles; Page Up/Page Down -->> bursts. Just an idea. Depending on keys, the appropriate button is highlighted. 

There could be other options. These are just ideas.

**For the bicycle pump** we could look at mapping that to a slider, going up/left is loading with air and going down/right is pumping out particles and increasing pressure. We could explore the standard types of slider shortcuts to pump a little or a lot.

**The Container Lid Handle** and **Container Resize Handle** appear like they would map well to a standard HTML slider interaction as well, though from #197 a particular kind of control over speed (or steps) seems very important. 

**The Collision Counter** like the Stopwatch is a composite widget, but the guts of it seem somewhat straight forward for Alt Input.

**Comment by pixelzoom** [comment]
Thanks for the input @terracoda.  There are now common-code issues for FineCoarseSpinner and BicyclePumpNode, so I've copied your comments to those issues.  Lets' continue component-specific discussion in those issues.

> The Container Lid Handle and Container Resize Handle appear like they would map well to a standard HTML slider interaction as well, though from https://github.com/phetsims/gas-properties/issues/197 a particular kind of control over speed (or steps) seems very important.

Thanks, but these are already implemented using DragListener and KeyboardDragListener, and are awaiting review.  The DragListeners are very complicated, and it relativley simple to use the standard pattern that we have for other places where we use DragListener -- that is, factor out code that can be used by both DragListener and KeyboardDragListener, and add a KeyboardDragListener.

> The Collision Counter like the Stopwatch is a composite widget, but the guts of it seem somewhat straight forward for Alt Input.

One of the "guts" of CollisionCounterNode is a ComboBox, which requires the arrow keys.  So what was done for StopwatchNode is problematic to apply to CollisionCounterNode. Specifically, a focus rectangle around the StopwatchNode and being able to move it while the the "guts" have focus conflicts with the need to use the arrow buttons to navigate the ComboBox:

<img width="281" alt="screenshot_3120" src="https://github.com/phetsims/gas-properties/assets/3046552/d6840783-9efd-498b-8d22-0aaf9a1c0a1e">

**Comment by pixelzoom** [comment]
Added to my comment about container lid & resize above:

I'll discuss with @arouinfar and the sim team whether we want to investigate converting these to AssessibleSlider -- it would be potentially destabilitizing, a lot of work, and we have a ton of other work for this release.

**Comment by pixelzoom** [comment]
Re: 

> > **The Collision Counter** like the Stopwatch is a composite widget, but the guts of it seem somewhat straight forward for Alt Input.
> 
> One of the "guts" of CollisionCounterNode is a ComboBox, which requires the arrow keys.  So what was done for StopwatchNode is problematic to apply to CollisionCounterNode. Specifically, keeping a focus highlight around the StopwatchNode and being able to move it while the "guts" have focus conflicts with the need to use the arrow buttons to navigate the ComboBox:

I added the group focus highlight to CollisionCounterNode in https://github.com/phetsims/gas-properties/commit/1cdd3740c262670166473b99a6b71aa79d9c9a6b, so it now looks like this:

<img width="215" alt="screenshot_3182" src="https://github.com/phetsims/gas-properties/assets/3046552/ec60e60f-9c1a-4361-a0c0-3e3977a36d77">

The ComboBox's listbox also has a group focus highlight. And while the listbox is popped up, CollisionCounterNode is not draggable.  So when the listbox is popped up, the CollisionCounterNode's group focus highlight disappears, as shown below.  When the listbox pops down, the group focus highlight re-appears on CollisionCounterNode's.  I consulted with @jessegreenberg about this, and he confirmed that this is the expected/desired behavior. 

<img width="191" alt="screenshot_3184" src="https://github.com/phetsims/gas-properties/assets/3046552/a4fdcfe7-9dcf-4bbd-99d9-f91cdacf7526">

**Comment by pixelzoom** [comment]
Design meeting with @arouinfar.... 

For the _Diffusion_ screen:

Play Area
1. Stopwatch
2. Data
3. Particle spinners

Control Area
4. Checkboxes (pull out into separate panel)
5. Time control
6. Reset All

**Comment by arouinfar** [comment]
@kathy-phet and I discussed focus order for the first 3 screens, and created the mockups below. We tried to balance prioritizing important actions early in the focus order and creating a coherent traversal order.  

I reviewed the mockups with @pixelzoom and we decided to use this as a starting place, so that the team can try it out and refine the order.

For the Ideal/Explore screens, we'd like to try this order, with the "Return Lid" coming in at 7b. The Control Area begins with the Temperature Units ComboBox, item 10.
![image](https://github.com/phetsims/gas-properties/assets/8419308/87d184c6-df46-453e-885c-e34414e14240)

For the Energy Screen, we'd like to try this order, again with the "Return Lid" button coming in at 7b. For consistency with previous screens, the control area begins with the Temperature Units CombobBox, item 12.
![image](https://github.com/phetsims/gas-properties/assets/8419308/37cf933b-1cef-47ed-b95a-c22fb1b7df35)

**Comment by pixelzoom** [comment]
I've set up the pdomPlayAreaNode.pdomOrder and pdomControlAreaNode.pdomOrder for all screens as requested above.

My 2 cents:
* If I'm a power user who is trying to quickly navigate the sim, this order is going to be frustrating, confusing, and unusable, because we're jumping all over the screen.
* Having some control panels in playArea and others in controlArea seems odd to me.  I guess I don't understand the a11y semantics/goals of playArea vs controlArea.

**Comment by pixelzoom** [comment]
@arouinfar and I reviewed the behavior of HeaterCoolerNode.  It's not really usable with the keyboard, needs work, see https://github.com/phetsims/scenery-phet/issues/853.

**Comment by pixelzoom** [comment]
Related to this issue, @arouinfar would like to revisit the order of the panels at the right edge of the Ideal, Explore, and Energy screens.

**Comment by pixelzoom** [comment]
In #259 and #260 we changes some things about the layout of panels, accordion boxes, and controls.  Ready for you to review and specify new traversal order.

**Comment by arouinfar** [comment]
@pixelzoom here's the focus order @Nancy-Salpepi and I discussed. 

For the Energy Screen, we decided to put the left-side accordion boxes before the container controls so that users can set up the view/what kind of data they are interested in early on in the experiment. 

## Ideal/Explore Screens

### Play Area
1. Particles AccordionBox
2. Hold Constant (Ideal only)
3. Container-related controls in clockwise order starting with the punp.
   * BicyclePumpNode
   * Species radio button group
   * Erase button
   * HeaterCoolerNode
   * Resize handle
   * Lid Handle
   * Thermometer ComboBox
   * Pressure ComboBox
4. Collision Counter Node
5. Stopwatch Node

### Control Area

6. Tools Panel
7. TimeControlNode
8. ResetAllButton

## Energy Screen

### Play Area

1. Particles AccordionBox
2. InjectionTemperature  AccordionBox
3. Average Speed AccordionBox
4. Speed AccordionBox
5. Kinetic Energy AccordionBox
6. Container-related controls in clockwise order starting with the punp.
   * BicyclePumpNode
   * Species radio button group
   * Erase button
   * HeaterCoolerNode
   * Lid Handle
   * Thermometer ComboBox
   * Pressure ComboBox
7. Stopwatch Node

### Control Area

8. Tools Panel
9. TimeControlNode
10. ResetAllButton

**Comment by pixelzoom** [comment]
Change for the first 3 screens have been completed. Back to @arouinfar and @Nancy-Salpepi to review.

Did you want any changes to the Diffusion screen? Here's the current order:

```ts
    // Play Area focus order, see https://github.com/phetsims/gas-properties/issues/213.
    this.pdomPlayAreaNode.pdomOrder = [
      stopwatchNode,
      dataAccordionBox,
      settingsPanel
    ];

    // Control Area focus order, see https://github.com/phetsims/gas-properties/issues/213.
    this.pdomControlAreaNode.pdomOrder = [
      toolsPanel,
      this.timeControlNode,
      this.resetAllButton
    ];
```

**Comment by arouinfar** [comment]
Thanks @pixelzoom, I think this a nice improvement over dev.10, and we strike a better balance between interaction order and visual order. I don't have any change requests. 

@Nancy-Salpepi @kathy-phet can you take the alt input for a spin?

**Comment by Nancy-Salpepi** [comment]
@pixelzoom @arouinfar 
I really like the order on the first 3 screens. It is really logical in terms of how users would interact in order to explore relationships and doesn't jump around too much.  

I find it a little odd that the expand/collapse button for the Data accordion box is first in the focus order on the Diffusion Screen (or the stopwatch if that is checked). The box is closed by default to allow for predictions/qualitative exploration. Making the expand/collapse button first in the focus order, gives the impression that it is really important and I should press the button to open the accordion box. Similarly, interacting with the Stopwatch before adding any particles or changing variables also seems strange. I think it might be better to start with the Particles Panel first on this screen as well. 

The hotkey for Play/Pause is going to be really useful when setting up experiments. It should be added to the Keyboard Shortcuts Dialog to remind users of it.

**Comment by pixelzoom** [comment]
@Nancy-Salpepi said:
> I find it a little odd that the expand/collapse button for the Data accordion box is first in the focus order on the Diffusion Screen (or the stopwatch if that is checked). ...

I agree with this, which is why I asked about changes to the Diffusion screen order in https://github.com/phetsims/gas-properties/issues/213#issuecomment-2168581779.

@arouinfar thoughts?

**Comment by kathy-phet** [comment]
I like Option 1 as well.

**Comment by kathy-phet** [comment]
And I agree with @Nancy-Salpepi here: 
> The hotkey for Play/Pause is going to be really useful when setting up experiments. It should be added to the Keyboard Shortcuts Dialog to remind users of it.

**Comment by Nancy-Salpepi** [comment]
I also like Option 1. It is more consistent with the other screens.

**Comment by pixelzoom** [comment]
Option 1 it is. @arouinfar please review, close if OK.

And note that keyboard help for Play/Pause was added in #215.

**Comment by arouinfar** [comment]
Looks good, thanks everyone! Closing.
