### ISSUE TITLE
Changes to examples.md

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/gas-properties#285]
- [x] Under "Hide one type of Particles" change:
    `gasProperties.idealScreen.view.viewProperties.particleTypeProperty` to `gasProperties.energyScreen.view.viewProperties.particleTypeProperty` 

I will continue to add to this issue if I find anything else.

**Comment by Nancy-Salpepi** [comment]
Tagging https://github.com/phetsims/qa/issues/1107

**Comment by pixelzoom** [comment]
@arouinfar Please consider waiting until you have a complete list of changes related to https://github.com/phetsims/qa/issues/1107, and making those changes as one commit to gas-properties main.  Since we're in RC, that commit will need to be patched into not only gas-properties 1.1, but new branches of gases-intro and diffusion.  I'll be happy to handle the patching, but dealing with 1 commit would make my life easier.

**Comment by Nancy-Salpepi** [comment]
These need to be featured:
`gasProperties.diffusionScreen.view.panels.settingsPanel.numberOfParticlesControls.visibleProperty` 
`gasProperties.diffusionScreen.view.panels.settingsPanel.massControls.visibleProperty`
`gasProperties.diffusionScreen.view.panels.settingsPanel.radiusControls.visibleProperty`
`gasProperties.diffusionScreen.view.panels.settingsPanel.initialTemperatureControls.visibleProperty`

**Comment by Nancy-Salpepi** [comment]
For Gases Intro (https://github.com/phetsims/qa/issues/1108):

Make the 'l' in LawScreen lowercase in the code snippet under **Access raw particle data**

**Comment by Nancy-Salpepi** [comment]
For Diffusion (https://github.com/phetsims/qa/issues/1109) the examples.md looks good. 
The visibleProperty for the diffusion variables has been fixed in #286

**Comment by arouinfar** [comment]
- [ ] The Maxwell-Boltzmann distribution example should refer clients to temperature data instead of speed data.

**Comment by pixelzoom** [comment]
Looks like QA has completed https://github.com/phetsims/qa/issues/1107, so @arouinfar can proceed with making changes. Assign to me when you're done, and I'll cherry-pick.

**Comment by arouinfar** [comment]
Thanks @Nancy-Salpepi! I've made the 3 changes identified in this issue along with some minor formatting tweaks. The Diffusion sim did not require any changes.

@pixelzoom the above commits are ready to cherry-pick.

**Comment by pixelzoom** [comment]
Release branches are patched.   Ready for verification in 1.1.0-rc.2.

**Comment by pixelzoom** [comment]
Please verify for https://github.com/phetsims/qa/issues/1123 and https://github.com/phetsims/qa/issues/1124.  (There were no changes for the Diffusion sim.)

If everything looks OK, please close this issue.

**Comment by Nancy-Salpepi** [comment]
Changes look good in rc.2 for Gas Properties and Gases Intro.
Closing.

**Comment by KatieWoe** [comment]
In the example doc for Gases Intro, there were some properties with incorrect capitalization. This does not impact searching. 
![caps](https://github.com/user-attachments/assets/4258ff5d-95e3-484d-8332-92d9ae068ee4)
From Slack:
> Amy Rouinfar

Since it doesn't affect searching, I'm inclined to leave it alone, assuming there isn't anything else to fix.
Regardless, reopen the issue because it should get fixed on main, even if we decide not to patch

**Comment by Nancy-Salpepi** [comment]
Oh man! Sorry I missed that @arouinfar!

**Comment by pixelzoom** [comment]
@arouinfar and I discussed. I fixed in the above commit, will cherry-pick next. We don't feel this is worthy of QA's time, and the QA Pipeline overfloweth. If no other problems are found, I'll publish 1.1.0-rc.3 and have @arouinfar verify, then publish production.

**Comment by pixelzoom** [comment]
@arouinfar please verify in https://phet-dev.colorado.edu/html/gases-intro/1.1.0-rc.3/phet-io/. Close if OK.

**Comment by arouinfar** [comment]
Looks good in rc.3, closing.
<img width="937" alt="image" src="https://github.com/user-attachments/assets/4529b664-b33d-4c80-8166-d22b07156004">
