### ISSUE TITLE
identify reusable UI components

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#29]
The design document has a list of UI components, but doesn't identify which are found in common-code, which need to be migrated to common-code from another sim, and which are specific to this sim.  

@arouinfar FYI, anything not shown in the table below will not be reused, and will be developed specifically for this sim. 

| UI component | repository | JS type | issue |
|:---|:---|:---|:---|
| Particle counts | scenery-phet | FineCoarseSpinner | https://github.com/phetsims/scenery-phet/issues/450 |
| Pressure gauge | scenery-phet | GaugeNode| |
| Heat bucket | scenery-phet | HeaterCoolerNode | |
| Thermometer | scenery-phet | ThermometerNode | |
| Bicycle pump | states-of-matter | BicyclePumpNode | https://github.com/phetsims/states-of-matter/issues/217 |
| Container handles | states-of-matter | HandleNode | https://github.com/phetsims/states-of-matter/issues/217 |
| Play/Pause button | scenery-phet | PlayPauseButton | |
| Step button | scenery-phet | StepButton | | 
| Dimensional arrows | ? | ? | https://github.com/phetsims/wave-interference/issues/79 |

**Comment by arouinfar** [comment]
@pixelzoom thanks for creating this table! It's only since working with the the creation of the style guide/binder that I've become more familiar with the technical names for some of these common-code components. Moving forward, I'll make it standard practice to identify which UI components are common-code (or will need to be migrated to common-code).

The only thing I would potentially add to this table is the Size arrow. However, there are still ongoing discussions about if/how such an arrow would be generalized into a common-code component.

**Comment by pixelzoom** [comment]
Size arrow (Dimensional arrows) was added to the table, with a link to the relevant issue.

**Comment by pixelzoom** [comment]
I'm currently re-using all of the above UI components. The one exception is `BicyclePumpNode`, which is still in development, see https://github.com/phetsims/states-of-matter/issues/217.

So I think it's safe to close this issue.  Assigning to @arouinfar in case she wants to capture the above table of components in the design doc.

**Comment by arouinfar** [comment]
Thanks @pixelzoom, the table in https://github.com/phetsims/gas-properties/issues/29#issue-342041928 has been added to the [Design Overview](https://docs.google.com/document/d/1HOCO6vXfqlHIf3MrdldaiZTPFKYWTzS9Jm8fw-b25EU/edit#) section of the design doc.
