### ISSUE TITLE
investigate code reuse options for histograms

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#43]
[Gas Properties HTML5](https://docs.google.com/document/d/1HOCO6vXfqlHIf3MrdldaiZTPFKYWTzS9Jm8fw-b25EU/edit#heading=h.gjdgxs) design document shows 2 histograms, for Speed and Kinetic Energy, in the _Energy_ screen:

<img width="625" alt="screenshot_1114" src="https://user-images.githubusercontent.com/3046552/54845602-69cc0480-4c9f-11e9-869a-cec8bd0f3956.png">

Is there anything that can be reused in common code, or generalized from another sim?

**Comment by samreid** [comment]
I'm not aware of pre-existing code that can be leveraged.  We may need a type for this --perhaps in griddle.

**Comment by pixelzoom** [comment]
A case insensitive search for "histogram" points me to plinko-probability and build-a-molecule.

In  plinko-probability, it's the "bins" that appear below the main apparatus.  This is not even close to a true histogram or what I need in Gas Properties.

Running build-a-molecule, I can't seem to locate the histogram. @jonathanolson can you please point me to where it appears in the UI, preferable with a screenshot?

**Comment by pixelzoom** [comment]
I investigated `ElementHistogram` in build-a-molecule, and it seems to be a model element only, with no visual histogram graph in the UI.  @jonathanolson is that correct?   Assuming that it is correct...

PhET has no common-code support for histograms, and there's nothing that I can reuse/steal from another sim.  PhET can't use a 3rd-party library due to PhET-iO and a11y requirements (see https://github.com/phetsims/tasks/issues/979).  So we need to create a histogram UI component.

@arouinfar @ariel-phet @kathy-phet  Please provide guidance on what you'd like me to do here.  Do you want a quick-and-dirty histogram that only works for Gas Properties?  Or do you want a general histogram that can be reused in future sims?  The former is ~2-3 days. The latter is an opened ended project requiring input from designers and other PhET developers.

**Comment by pixelzoom** [comment]
I asked:
> Do you want a quick-and-dirty histogram that only works for Gas Properties? Or do you want a general histogram that can be reused in future sims?

My recommendation is the first option - create a histogram that meets the needs of Gas Properties and lives in the gas-properties repo.  I'm recommending this option because I don't have the time (or interest) in the second option.  And (more importantly) the second option should be done in the larger context of a charting library, which is something that PhET clearly needs.

**Comment by arouinfar** [comment]
@pixelzoom this seems like the first true histogram in a sim, so the approach would be a GasProps-specific histogram. Usually we don't generalize a component until its 2nd appearance in a sim. At that point, it's a bit easier to decide on the general features and options of the common component, since you have two potentially different use cases in mind.

The first option seems most reasonable to me at this stage, but it would still be good for @ariel-phet (and possibly @kathy-phet) to weigh in.

**Comment by ariel-phet** [comment]
@pixelzoom agreed, go "quick and dirty" - I think you have a pretty good eye for things so feel free to make things a bit more general in places where you see appropriate.

Two options I could see worth adding while you are doing this work (but certainly not necessary, only if they are easy...) would be:
1. Allowing for "stroked bars" (sometimes you see this on histograms). Again not necessary, but might be a useful option 
2. Tick marks on the graph axes

Otherwise, I am not aware of any sims on the horizon that should need any serious histogram functionality, so making this feature tailored specifically to Gas Props is totally appropriate, and as @arouinfar said we can generalize when the next case comes up.

**Comment by pixelzoom** [comment]
Sounds good, I'll proceed with an implementation that is specific to Gas Properties, but generalizable.

**Comment by kathy-phet** [comment]
Just for the record, I also agree - quick and dirty histogram is best for this sim. This will help us with some groundwork if/when we do have other sims with this need.
