### ISSUE TITLE
consider revising color profile for panels

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#48]
To my eye, there's too much negative space in this sim, everything has the same background color.  And that causes a "boxes inside of boxes" look.  That could be resolved by giving the panels a background color that is different from the screen background color. If you want to play around with this yourself, open gas-properties/gas-properties-colors.hmtl (master) in a browser.

For example, here's the Explore screen in 'default' and 'projector' with this color profile:

```js
    // fill for control panels
    panelFill: {
      default: 'black',
      projector: 'white'
    },
```

![screenshot_134](https://user-images.githubusercontent.com/3046552/55440898-586bdd80-5566-11e9-8bf8-68a7494b26b9.png)

![screenshot_135](https://user-images.githubusercontent.com/3046552/55440905-5b66ce00-5566-11e9-9b0b-e4221070a490.png)

Here's the same screen with a color profile that gives control panels a different fill color than the screen background (shades of gray):

```js
    // fill for control panels
    panelFill: {
      default: 'rgb( 40, 40, 40 )',
      projector: 'rgb( 220, 220, 220 )'
    },
```

![screenshot_133](https://user-images.githubusercontent.com/3046552/55440999-a254c380-5566-11e9-96f1-5a704b1ea301.png)

![screenshot_131](https://user-images.githubusercontent.com/3046552/55441005-a54fb400-5566-11e9-8a6e-019f18e70082.png)

**Comment by pixelzoom** [comment]
Thought I prefer the above dark gray panels, this even looks better to me than the current default profile, and might have made the added overhead/cost of "projector mode" unnecessary.   

![screenshot_136](https://user-images.githubusercontent.com/3046552/55441407-07f57f80-5568-11e9-99cb-b50b63d626d7.png)

**Comment by pixelzoom** [comment]
Added meeting:design label, would be good to discuss this while I'm on vacation.

**Comment by pixelzoom** [comment]
@arouinfar I think it would be good to make progress on this soon. Otherwise we may get too used to seeing the current color scheme and lose our objectivity.

**Comment by arouinfar** [comment]
Let's review in tomorrow's design meeting.

**Comment by arouinfar** [comment]
This issue has been tabled for awhile, but it would be good to make a decision soon. I do like the light gray panels in https://github.com/phetsims/gas-properties/issues/48#issuecomment-479242716, so that would be my preference if we decide to give the panels a different fill. The nice thing about the gray is that it works for the standard and projector modes, and would alleviate the so-called  "boxes inside of boxes"  look.

@pixelzoom can you push the light gray panels to master, and then reassign to me, @kathy-phet, and @ariel-phet for review?

**Comment by pixelzoom** [comment]
Color profile has been revised to support panels with fill `rgb( 220, 220, 220 )`.

Test drive in [1.0.0-dev.23](https://phet-dev.colorado.edu/html/gas-properties/1.0.0-dev.23/phet/gas-properties_en_phet.html).

If you want to do further tweaking, use gas-properties-colors.html in master.

**Comment by pixelzoom** [comment]
Observations:
* icons for the blueish particles in the Diffusion screen are a bit washed out, see screenshot below
* it might be nice to make the Data accordion box contents look like the container,see screenshot below

<img width="1072" alt="screenshot_1197" src="https://user-images.githubusercontent.com/3046552/57947183-76359d80-789b-11e9-8776-f1032fa4c1a9.png">

**Comment by ariel-phet** [comment]
I cannot say I really like the light gray panels, it just feels too heavy to me in this sim. If I were going to go for a different look, I would opt for no stroke on the panels and a dark background that is lightened up enough to allow a contrast, but still blend with the rest of the sim. For example:

![gas props](https://user-images.githubusercontent.com/4051174/58036594-b178dc00-7ae8-11e9-9aeb-93c11c6ae779.PNG)

Otherwise the panels just feel too blocky and overwhelming (IMO)

**Comment by pixelzoom** [comment]
@ariel-phet That looks good to me.  Could you please clarify what you're recommending for projector mode?  Light panels with no stroke?

**Comment by ariel-phet** [comment]
Sounds like @arouinfar likes the general direction, and will play with the color profile for specific recommendations.

**Comment by kathy-phet** [comment]
I like the general direction of the darker grey panels. 

BTW, I demoed this sim this weekend (with the black panels), and the audience loved it ... especially the KMT screen with the 2 speed and energy distributions shown!

**Comment by arouinfar** [comment]
As @ariel-phet mentioned, I liked the direction of the darker panels, so I experimented a bit more using gas-properties-colors.html in master.  For projector mode, I think a light gray panel works well and has a similar feeling to the dark gray used in the standard mode. I also adjusted the cyan particle color on the Diffusion screen so it a bit more blueish, which I think improves the contrast against the white background and light gray panel.


Here are some comparison screenshots

![Gas Properties screenshot-1a](https://user-images.githubusercontent.com/8419308/58048772-94540580-7b08-11e9-9ae1-43ddc03ba0ef.png)
![Gas Properties screenshot-1b](https://user-images.githubusercontent.com/8419308/58048773-94ec9c00-7b08-11e9-930a-da332624b089.png)
![Gas Properties screenshot-3a](https://user-images.githubusercontent.com/8419308/58048775-94ec9c00-7b08-11e9-886d-c0208cb324d9.png)
![Gas Properties screenshot-3b](https://user-images.githubusercontent.com/8419308/58048776-94ec9c00-7b08-11e9-82ff-3c45e6e51d0b.png)
![Gas Properties screenshot-4a](https://user-images.githubusercontent.com/8419308/58048777-94ec9c00-7b08-11e9-9b23-5f377df7a39d.png)
![Gas Properties screenshot-4b](https://user-images.githubusercontent.com/8419308/58048778-94ec9c00-7b08-11e9-808e-1c31d6d6a5be.png)


| Element | Standard | Projector Mode |
| --- | --- | --- |
| checkboxFill | `rgb( 0, 0, 0 )` | no change |
| checkboxStroke | `rgb( 255, 255, 255 )` | no change |
| panelFill | `rgb( 40, 40, 40 )` | `rgb( 235, 235, 235 )` |
| panelStroke^ | `rgb( 0, 0, 0 )` | `rgb( 255, 255, 255 )` |
| particle1Color | `rgb( 0, 230, 255)` | `rgb( 0, 230, 255)` |
| widthIconColor | `rgb( 255, 255, 255 )` | no change |

^  I set the `panelStroke` to match the `screenBackgroundColor` since there isn't an explicit option to set it to none.

**Comment by ariel-phet** [comment]
I think this all looks great

**Comment by pixelzoom** [comment]
I think this looks great too, and I've pushed the changes to master.  

One suggested improvement is to use a very subtle stroke for the panels, just slightly brighter/darker than the panel fill.  This gives crispness to the edges.  I have not checked this in, but something like:

```js
    // stroke for control panels
    panelStroke: {
      default: 'rgb( 55, 55, 55 )',
      projector: 'rgb( 220, 220, 220 )'
    },
```

Examples:

<img width="858" alt="screenshot_1202" src="https://user-images.githubusercontent.com/3046552/58051513-9f5e6400-7b0f-11e9-83ea-390c1fdab750.png">

<img width="853" alt="screenshot_1203" src="https://user-images.githubusercontent.com/3046552/58051519-a2595480-7b0f-11e9-9a07-aff3781021fa.png">

**Comment by arouinfar** [comment]
> One suggested improvement is to use a very subtle stroke for the panels, just slightly brighter/darker (depending on mode) than the panel fill. This gives crispness to the edges. I have not checked this in, but something like:

I think that looks really nice @pixelzoom! Definitely still subtle, but adds some depth. Please make the changes in master.

**Comment by pixelzoom** [comment]
Done!

**Comment by pixelzoom** [comment]
@arouinfar feel free to close if there's nothing left to do here.

**Comment by arouinfar** [comment]
Looks wonderful, thanks!
