### ISSUE TITLE
particle waves when Collisions are off

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#69]
When particle collisions are off in the Energy screen, we give all particles in a group an identical temperature.  This results in wave-like motion.   I wanted to make sure that was really what is desired, and that someone had taken a look at it, because it looks odd to me.

To demonstrate:

1. Start the sim
2. Go to Energy screen
3. Expand the Particle Tools accordion box
4. Uncheck the Collisions checkbox
5. Expand the Particle Counts accordion box 
6. Add a group of heavy particles, wait a few seconds, then add another group.

The particles that we added together will all move together for quite awhile, which looks very different.  I'm not sure why this is relevant to collisions being off.

**Comment by arouinfar** [comment]
Thanks for checking @pixelzoom. The current behavior with particle collisions off truly is the desired behavior. It looks strange, but that's because it's a non-physical situation. 

This feature is meant to support students learning about the KE/speed distributions. Particle-particle collisions result in variations in speed/KE due to momentum transfer, and without collisions, there is no distribution.

> The particles that we added together will all move together for quite awhile, which looks very different. I'm not sure why this is relevant to collisions being off.

There is no momentum transfer during particle-wall collisions, so the particle's inbound speed will match its outbound speed, and the angle of trajectory is reflected. Since the particles originate in a group, it will take several particle-wall collisions to redirect the trajectories enough to break up the group.
