### ISSUE TITLE
behavior of "work" model

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gas-properties#71]
Starting with [1.0.0-dev.21](https://phet-dev.colorado.edu/html/gas-properties/1.0.0-dev.21/phet/gas-properties_en_phet.html), the left wall in the _Explore_ screen does work on particles.  

Velocity of the left wall is computed continuously while the sim is running, based on current position, previous position, and dt.  That velocity is of course totally x component, with zero y component.  If you run with `?log`, you'll see `leftWallVelocity.x` values (in pm/ps) printed to the browser console as you resize the container. 

Following a collision with the moving wall, the new x component of a particle's velocity is:
`-( particleVelocity.x - leftWallVelocity.x )`, in pm/ps.

Observed with a single (or a few) particles, this seems to be working nicely.  E.g. if both the wall and particle are moving to the left, after a collision the particle moves to the right with reduced velocity.  And moving the wall to the right also seems to have the desired effect on particle velocity.  But if you move the wall to the right too quickly, it's very easy (too easy?) to blow the lid off of the container.

@arouinfar please review and let me know what you think.

**Comment by pixelzoom** [comment]
5/16/19 status meeting, @arouinfar and @kathy-phet suggested that we put a speed limiter on the moveable wall, similar to the lid in SOM.

**Comment by arouinfar** [comment]
@pixelzoom @kathy-phet I've reviewed the behavior in dev.21 quite a bit, and it's behaving as expected.

| Speed | Direction | Behavior |
| --- | --- | --- | 
| Fast | Compression | Large increase in T | 
| Fast | Expansion | No change in T |
| Slow | Compression | Gradual increase in T |
| Slow | Expansion | Gradual decrease in T |

I do think that a speed limit is probably the way to go, but I it will take a bit of a balance to find the sweet spot. The speed limit should be high enough that we can still observe a "fast" expansion with no change in T, but it should be possible to keep the lid on the container after correspondingly "fast" compression (assuming starting at default V & T, N ~ 300). 

I did some quick calculations, and a speed limit of 1000 pm/ps may a good starting point. The speed limit will likely take some tuning, so a query parameter would also be helpful.

A few other thoughts I have about the wall behavior that I'd like team feedback on.
* I don't think we need a speed limit on the Ideal screen. The nature of moving the wall is very different there, and the difference in UX may help users realize that the walls are different.
* Showing the original wall position seems unnecessary on Explore. It looks a bit strange to me because the particles continue to move, and can pass through the ghost wall.

**Comment by pixelzoom** [comment]
5/16/19 design meeting @arouinfar @kathy-phet:

- [ ] add speed limit for resizing, with query parameter
- [ ] no speed limit on Ideal screen, but possible to add one 
- [ ] no "previous container" size on Explore screen

**Comment by pixelzoom** [comment]
Speed limit feature moved to #90.  Closing.
