### ISSUE TITLE
Red particles jammed on iPhone

### ISSUE THREAD

**Issue by samreid** [phetsims/gas-properties#75]
I tested [1.0.0-dev.22](https://phet-dev.colorado.edu/html/gas-properties/1.0.0-dev.22/phet/gas-properties_en_phet.html) and after a minute or so on the first screen, the red particles became jammed:

![image](https://user-images.githubusercontent.com/679486/57856726-d39df180-77aa-11e9-84f4-80df86b02527.png)

Note in the image there are supposedly 600 red particles at the moment.  I believe they were getting jammed at the output site of the pump.  I tried pumping more and even though the readout went up to 1000, the picture looked the same.  After waiting several minutes, they are still jammed.  I cleared the blue particles and pumped in 471 blue particles, but they jammed at the site as well.  A few of them escaped on the bottom side, but I think most are stuck:

![image](https://user-images.githubusercontent.com/679486/57857050-8c643080-77ab-11e9-952f-52aff61bf489.png)

I did not make an effort to reproduce the problem, but thought I should report it as a sighting.

**Comment by pixelzoom** [comment]
1.0.0-dev.22 had a problem with BicyclePumpNode that was causing particles to get stuck and causing  the max number of particles to be exceeded.  That's been fixed in master.  

I also see that "Pressure T" was selected for "Hold Constant", and we're still working the kinks out of how that's supposed to behave.    

So I'm going to close this, and we can reopen if something similar resurfaces.
